# -*- coding: utf-8 -*-
"""intro_scikit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CsMAbKkzTtxaE2KxDweatJQSZ2DkaMyb
"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt
import numpy as np

import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

database = files.upload()

df = pd.read_csv('data_1.csv')

df.rename(columns={'0': 'X', '0.1' : 'Y'}, inplace=True)

df.head()

df.plot.scatter(x = 'X', y = 'Y')

df = df[(df.X > 1) & (df.Y > 50) & (df.Y < 275)]

df.plot.scatter(x = 'X', y = 'Y')

X = pd.DataFrame(df['X'])
Y = pd.DataFrame(df['Y'])

data = df

X_train = X[:-20]
X_test = X[-20:]

Y_train = Y[:-20]
Y_test = Y[-20:]

regr = linear_model.LinearRegression()

regr.fit(X,Y)

Y_pred = regr.predict(X)

print('Coefficients: \n', regr.coef_)

plt.scatter(X_test, Y_test,  color='black')
plt.plot(X_test, Y_pred, color='blue', linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()

